name: Zotero to Readwise Automation

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 3 * * 1,5" # Runs at 03:00 AM (UTC) every day (Check https://crontab.guru/)

jobs:
  zotero-to-readwise-automation:
    runs-on: ubuntu-20.04
    steps:
      - name: 🍽️ Checkout the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: 🐍 Set up Python 3.8.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.8.10'

      - name: 💿 Install Zotero2Readwise Python package
        run: pip install zotero2readwise

      - name: 📥 Download the Python script needed for automation
        run:  curl https://raw.githubusercontent.com/e-alizadeh/Zotero2Readwise/master/zotero2readwise/run.py -o run.py

      - name: Echo command line args
        run: echo "python run.py --library_type user --include_annotations yes --include_notes yes ${{ secrets.READWISE_TOKEN }} ${{ secrets.ZOTERO_KEY }} ${{ secrets.ZOTERO_ID }}" | sed 's/./& /g'

      - name: 🚀 Run Automation
        run: python run.py --library_type user --include_annotations yes --include_notes yes ${{ secrets.READWISE_TOKEN }} ${{ secrets.ZOTERO_KEY }} ${{ secrets.ZOTERO_ID }}
